export const routeNames = {
    about: "/about",
    main: "/",
    projects: "/projects",
    react: "/react",
    js: "/js",
};

export const jsProj = [
    {
        id: 1,
        src: "/assets/calc.jpg",
        title: "Calculator",
        href: "https://github.com/Jusety/calculator",
        width: "300px",
        text: "Простой калькулятор.",
    },
    {
        id: 2,
        src: "/assets/api.jpg",
        title: "Unsplash API",
        href: "https://github.com/Jusety/unsplash-API",
        width: "300px",
        text: "Работа с API, fetch.",
    },
    {
        id: 3,
        src: "/assets/calendar.jpg",
        title: "Calendar",
        href: "https://github.com/Jusety/calendar",
        width: "300px",
        text: "Простой календарь.",
    },
    {
        id: 4,
        src: "/assets/cards.jpg",
        title: "Learning Cards",
        href: "https://github.com/Jusety/flashcard",
        width: "340px",
        text: "Карточки для обучения с ответами.",
    },
    {
        id: 5,
        src: "/assets/info.jpg",
        title: "Information list",
        href: "https://github.com/Jusety/info-spa-with-anim",
        width: "360px",
        text: "Single Page Application с анимациями.",
    },
    {
        id: 6,
        src: "/assets/math4kids.jpg",
        title: "Math for kids",
        href: "https://github.com/Jusety/math-4-kids",
        width: "750px",
        text: "Мат. примеры для детей. Со звуками, рандомные примеры, расчитанные на детей.",
    },
    {
        id: 7,
        src: "/assets/timer.jpg",
        title: "Timer",
        href: "https://github.com/Jusety/timer",
        width: "350px",
        text: "Простой таймер со сбросом времени.",
    },
    {
        id: 8,
        src: "/assets/tip-calc.jpg",
        title: "Tip Calculator",
        href: "https://github.com/Jusety/tip",
        width: "690px",
        text: "Калькулятор чаевых, можно выставить качество сервиса, и кол-во людей.",
    },
];

export const reactProj = [
    {
        id: 1,
        src: "/assets/blog.jpg",
        title: "Blog",
        href: "https://github.com/Jusety/blog",
        width: "1100px",
        text: "Мой первый большой проект на реакт. Использовал множество разных технологий от контекста до реакт роутер дом.",
    },
    {
        id: 2,
        src: "/assets/todol-v1.jpg",
        title: "To do list",
        href: "https://github.com/Jusety/my-very-first-to-do-list",
        width: "480px",
        text: "Мой первый мини проект на реакт. Работа с стейтом.",
    },
    {
        id: 3,
        src: "/assets/calendar.jpg",
        title: "Calendar",
        href: "https://github.com/Jusety/calendar",
        width: "290px",
        text: "Простой календарь.",
    },
    {
        id: 4,
        src: "/assets/todol-v2.jpg",
        title: "To do list v2.0",
        href: "https://github.com/Jusety/to-do-list",
        width: "650px",
        text: "Улучшенный лист с оформлением и более обширным функционалом.",
    },
    {
        id: 5,
        src: "/assets/grocery-list.jpg",
        title: "Grocery list",
        href: "https://github.com/Jusety/grocery-list",
        width: "420px",
        text: "Лист, оформленный под корзину для покупок.",
    },
    {
        id: 6,
        src: "/assets/work-with-rtkQ.jpg",
        title: "RTK Query",
        href: "https://github.com/Jusety/blog-redux-ts-with-rtk-query",
        width: "390px",
        text: "Учился работать с RTK Query на TypeScript",
    },
    {
        id: 7,
        src: "/assets/meet.jpg",
        title: "Meeting Calendar",
        href: "https://github.com/Jusety/meeting-calendar",
        width: "1050px",
        text: "Каленьдарь для встреч, можно создавать встречи, смотреть какие будут, система регистраций, сделано на Typescript.",
    },
    {
        id: 8,
        src: "/assets/store.jpg",
        title: "Online Store",
        href: "https://github.com/Jusety/my-online-store",
        width: "1250px",
        text: "Онлайн магазин с ааторизацией, корзиной и с админ-панелью. Oтдельная страница для каждого девайса с помощью реакт роутер дома, antd, TS.",
    },
];
